from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name = 'pages-home'),
    path('bize-ulasin',views.bize_ulasin,name='pages-ulasin'),
    path('hakkimizda',views.hakkimizda, name='page-hakkimizda'),
    path('ozon-hakkinda',views.ozon_hakkinda,name='ozon-hakkinda'),
    path('nedir',views.nedir, name='nedir'),
    path('etki',views.etki,name='etki'),
    path('tarih',views.tarih,name='tarih'),
    path('dunya',views.dunya,name="dunya"),
    path('ozon-terapi',views.ozonterapi,name='ozon-terapi'),
    path('tedavi-edilen-hastaliklar',views.hastaliklar,name='hastaliklar'),
    path('tedavi-yontemleri',views.tedaviYontemleri,name='tedavi-yontemleri'),
    path('etki-mekanizmasi',views.etkiMekanizmasi,name='etki-mekanizmasi'),
    path('kimlere-uygulanmaz',views.kimlereUygulanmaz,name='kimlere-uygulanmaz'),
    path('tedavi-resim',views.tedaviResim,name='tedavi-resim'),
    path('ozon-sauna',views.sauna,name='sauna'),
    path('ozonlu-urunler',views.urunler,name='urunler'),
    path('iyi-gunde-ozon',views.iyi,name='iyi'),
    path('kotu-gunde-ozon',views.kotu,name='kotu'),
    path('uygulama',views.uygulama,name='uygulama'),
    path('dahiliye',views.dahiliye,name='dahiliye'),
    path('cerrahi',views.cerrahi,name='cerrahi'),
    path('ortepedi',views.ortepedi,name='ortepedi'),
    path('kadin-dogum',views.kadin_dogum,name='kadin-dogum'),
    path('enfeksiyon',views.enfeksiyon,name='enfeksiyon'),
    path('cilt',views.cilt,name='cilt'),
    path('solunum',views.solunum,name='solunum'),
    path('seker',views.seker,name='seker'),
    path('kanser',views.kanser,name='kanser'),
    path('hepatit',views.hepatit,name='hepatit'),
]